services:
  nordvpn:
    image: ghcr.io/bubuntux/nordlynx
    container_name: nordvpn
    cap_add:
      - NET_ADMIN
      - NET_RAW
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=1
    environment:
      - CONNECT=United_States
      - TECHNOLOGY=NordLynx
      - TZ=${TZ}
      - PUID=${PUID}
      - PGID=${PGID}
      - NET_LOCAL=192.168.10.0/24
    env_file:
      - /home/dan/config/vpn/nordvpn_credentials.env
    volumes:
      - /home/dan/config/nordvpn:/config
    ports:
      - 8112:8112  # Deluge
      - 8080:8080  # SABnzbd
      - 8989:8989  # Sonarr
      - 7878:7878  # Radarr
      - 8686:8686  # Lidarr
      - 9696:9696  # Prowlarr
    restart: unless-stopped

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    network_mode: service:nordvpn
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/deluge:/config
      - /mnt/disk_1tb/downloads:/downloads
    restart: unless-stopped

  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    network_mode: service:nordvpn
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/sabnzbd:/config
      - /mnt/disk_1tb/downloads:/downloads
    restart: unless-stopped

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    network_mode: service:nordvpn
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/sonarr:/config
      - /mnt/nfs/tv:/tv
      - /mnt/disk_1tb/downloads:/downloads
    restart: unless-stopped

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    network_mode: service:nordvpn
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/radarr:/config
      - /mnt/nfs/movies:/movies
      - /mnt/disk_1tb/downloads:/downloads
    restart: unless-stopped

  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    network_mode: service:nordvpn
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/lidarr:/config
      - /mnt/nfs/music:/music
      - /mnt/disk_1tb/downloads:/downloads
    restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    network_mode: service:nordvpn
    depends_on:
      nordvpn:
        condition: service_started
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/prowlarr:/config
    restart: unless-stopped

  profilarr:
      image: santiagosayshey/profilarr:latest # Use :beta for early access to new features
      container_name: profilarr
      ports:
        - 6868:6868
      volumes:
        - /home/dan/config/profilarr:/config
      environment:
        - PUID=${PUID}
        - PGID=${PGID}
        - TZ=${TZ}
      restart: unless-stopped

  overseerr:
    image: lscr.io/linuxserver/overseerr:latest
    container_name: overseerr
    ports:
      - 5055:5055
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - /home/dan/config/overseerr:/config
    restart: unless-stopped
